//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Pratica10(

    //////////// CLOCK //////////
    input                   MAX10_CLK1_50,

    //////////// KEY //////////
    input           [1:0]   KEY,

    //////////// SW //////////
    input           [9:0]   SW,

    //////////// HEX (Displays) //////////
    output          [7:0]   HEX0,
    output          [7:0]   HEX1,
    output          [7:0]   HEX2,
    output          [7:0]   HEX3,
    output          [7:0]   HEX4,
    output          [7:0]   HEX5,
 
    //////////// VGA //////////
    output          [3:0]   VGA_B,
    output          [3:0]   VGA_G,
    output                  VGA_HS,
    output          [3:0]   VGA_R,
    output                  VGA_VS
);

   
    // DECLARAÇÃO DE SINAIS
   
    wire clk, async_rstn, sync_rstn, video_on, pixel_tick, right_k, left_k;
    wire [9:0] pixel_x, pixel_y;
    reg  [11:0] rgb_reg;
    wire [11:0] rgb_next;
    wire [3:0] score; 

    assign clk = MAX10_CLK1_50;
    assign async_rstn = ~SW[0]; // Reset assíncrono na chave SW0

    // INSTANCIAÇÃO DOS MÓDULOS DE LÓGICA E VGA
    

    // Sincronizador de Reset
    AsyncInputSynchronizer u_sync (
        .clk(clk), 
        .asyncn(async_rstn), 
        .syncn(sync_rstn)
    );
     
    // Detector de Borda para Botão Direito (KEY0)
    EdgeDetector right_key (
        .clk(clk), 
        .rstn(sync_rstn), 
        .trigger(~KEY[0]), 
        .pulse(right_k)
    );
                                    
    // Detector de Borda para Botão Esquerdo (KEY1)
    EdgeDetector left_key (
        .clk(clk), 
        .rstn(sync_rstn), 
        .trigger(~KEY[1]), 
        .pulse(left_k)
    );

    // Sincronizador VGA
    VGASync vsync_unit (
        .clk(clk), 
        .rstn(sync_rstn), 
        .hsync(VGA_HS), 
        .vsync(VGA_VS), 
        .video_on(video_on), 
        .p_tick(pixel_tick), 
        .pixel_x(pixel_x), 
        .pixel_y(pixel_y)
    );
    
    // Gerador de Pixels (Jogo)
    PixelGen px_gen (
        .clk(clk), 
        .rstn(sync_rstn), 
        .video_on(video_on),
        .p_tick(pixel_tick),
        .right_k(right_k), 
        .left_k(left_k), 
        .pixel_x(pixel_x), 
        .pixel_y(pixel_y),
        .r(rgb_next[11:8]), 
        .g(rgb_next[7:4]), 
        .b(rgb_next[3:0]),
        .score(score) // Recebe a pontuação aqui
    );

    
    // SAÍDA DE VÍDEO (BUFFER)
    
    always@(posedge clk) begin
        if(pixel_tick)
            rgb_reg <= rgb_next;
    end
            
    assign {VGA_R, VGA_G, VGA_B} = rgb_reg;

    // CONTROLE DOS DISPLAYS DE 7 SEGMENTOS
   
    // Display HEX0: Mostra a pontuação (Unidade)
    SEG7_LUT u_seg0 (
        .iDIG(score),      // Entrada: Valor do score
        .oSEG(HEX0[6:0])   // Saída: Segmentos A-G
    );
    assign HEX0[7] = 1'b1; // Ponto decimal desligado

    
   
    assign HEX1[7] = 1'b1; // Ponto decimal desligado

    // Desligar displays não utilizados (Ativo Baixo: 1 = Apagado)
    assign HEX2 = 8'hFF;
    assign HEX3 = 8'hFF;
    assign HEX4 = 8'hFF;
    assign HEX5 = 8'hFF;

endmodule

// MÓDULO AUXILIAR: DECODIFICADOR 7 SEGMENTOS
// (Incluído no mesmo arquivo para evitar erro de "Undefined Entity")

module SEG7_LUT (
    input  [3:0] iDIG, 
    output reg [6:0] oSEG
);
    always @(*) begin
        case (iDIG)       // gfe_dcba
            4'h0: oSEG = 7'b100_0000;
            4'h1: oSEG = 7'b111_1001;
            4'h2: oSEG = 7'b010_0100;
            4'h3: oSEG = 7'b011_0000;
            4'h4: oSEG = 7'b001_1001;
            4'h5: oSEG = 7'b001_0010;
            4'h6: oSEG = 7'b000_0010;
            4'h7: oSEG = 7'b111_1000;
            4'h8: oSEG = 7'b000_0000;
            4'h9: oSEG = 7'b001_0000;
            4'hA: oSEG = 7'b000_1000;
            4'hB: oSEG = 7'b000_0011;
            4'hC: oSEG = 7'b100_0110;
            4'hD: oSEG = 7'b010_0001;
            4'hE: oSEG = 7'b000_0110;
            4'hF: oSEG = 7'b000_1110;
            default: oSEG = 7'b111_1111;
        endcase
    end
endmodule
